### ISSUE TITLE
log messages aren't escaped

### ISSUE THREAD

**Issue by DannyS712** [bd808/SAL#10]
See https://sal.toolforge.org/log/D4yd03UBgTbpqNOm4KOR - I tried to redact the log entry with `<redacted>`, but the output thinks that `<redacted>` should be part of the DOM and adds it there. I couldn't figure out where the relevant logic is, so not submitting a patch myself, but it should be escaped.

**Comment by supertassu** [comment]
This is [T267572](https://phabricator.wikimedia.org/T267572) and was fixed in 3a7cf48.
