### ISSUE TITLE
Spaces are deleted between consecutive links in the web interface

### ISSUE THREAD

**Issue by framawiki** [bd808/SAL#7]
See for example the absence of space between phab links in https://tools.wmflabs.org/sal/log/AWXpJGDhwY2u4JUTVyIb although that's not what was present in the irc message, as it can be seen on the [phabricator comment](https://phabricator.wikimedia.org/T204430#4591020).

**Comment by bd808** [comment]
Raw HTML looks like:
```
<td class="message">deployed till <a href="https://gerrit.wikimedia.org/r/#/q/e59152e,n,z" target="_blank">e59152e</a><a href="https://phabricator.wikimedia.org/T192696" target="_blank">T192696</a><a href="https://phabricator.wikimedia.org/T204432" target="_blank">T204432</a><a href="https://phabricator.wikimedia.org/T204226" target="_blank">T204226</a><a href="https://phabricator.wikimedia.org/T204430" target="_blank">T204430</a> to quarry-web-01</td>
```
So it looks like over aggressive whitespace pruning in the templates that generate the page.

**Comment by bd808** [comment]
Fix deployed! Thanks for reporting @framawiki.

**Comment by framawiki** [comment]
Thanks for the fix !
